version: "3.9"

services:
  web:
    build: .
    command: gunicorn --worker-class gthread --threads 4 --workers 1 --bind 0.0.0.0:5000 run:app
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/foodsprint
      REDIS_URL: redis://redis:6379/0
      APP_BASE_URL: http://127.0.0.1:5000
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: foodsprint
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
